# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd0f2c8231be40f63aaa209dcd2ad5445d7e3d8361550f222f8ea35056d4aa5cea5e733d329b5351d3164420e3cd28d88696b2dddec455844836549666891ce

test:
  secret_key_base: 4988aa6d3c8cc5bdbd99150b4991c306444b2ffe4c853346bf09f4af149bd327b8dd7be48249740dda1c3397440b4ee53c3d6f118923d254cbb8c03e85b738f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
